ALTER TABLE "PlaidAccount"
ADD COLUMN "monthlyContribution" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "annualReturnRate" DOUBLE PRECISION NOT NULL DEFAULT 0.07,
ADD COLUMN "forecastInputsUserEdited" BOOLEAN NOT NULL DEFAULT false;
